services:
  postgres:
    image: postgres:15-alpine
    container_name: myapp-postgres
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d myapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

#  product-service:
#    build:
#      context: ../backend/product-service
#      dockerfile: Dockerfile
#    container_name: product-service
#    ports:
#      - "8070:8070"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myapp
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: root
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  user-service:
#    build:
#      context: ../backend/user-service
#      dockerfile: Dockerfile
#    container_name: user-service
#    ports:
#      - "8071:8071"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myapp
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: root
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  order-service:
#    build:
#      context: ../backend/order-service
#      dockerfile: Dockerfile
#    container_name: order-service
#    ports:
#      - "8072:8072"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myapp
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: root
#    depends_on:
#      postgres:
#        condition: service_healthy

volumes:
  postgres_data: