
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
server:
  port: 8070

# application.yml
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
